---
# tasks file for wordpress

# WordPress Configuration
- name: create dir and download wp
  block: 
    - name: create /var/www/{{ server_name }} directory for unarchiving
      file:
        path: /var/www/{{ server_name }}
        state: directory

    - name: Download and unpack latest WordPress
      unarchive:
        src: https://wordpress.org/wordpress-5.7.1.tar.gz
        dest: "/var/www/{{ server_name }}"
        remote_src: yes
        creates: "/var/www/{{ server_name }}/wordpress"
      tags: [ wpdownload ]
  ignore_errors: no

- name: Set ownership
  file:
    path: "/var/www/{{ server_name }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data

- name: Set permissions for directories
  shell: "/usr/bin/find /var/www/{{ server_name }}/wordpress/ -type d -exec chmod 750 {} \\;"
  tags: [ chmod, chmoddir ]

- name: Set permissions for files
  shell: "/usr/bin/find /var/www/{{ server_name }}/wordpress/ -type f -exec chmod 640 {} \\;"
  tags: [ chmod, chmodfile ]

- name: Set up wp-config
  template:
    src: "wp-config.php.j2"
    dest: "/var/www/{{ server_name }}/wordpress/wp-config.php"
  tags: [ wordpress ]

